project_id = "burxedzkpugyavsqkzaj"

[functions.extract-resume-data]
verify_jwt = false

[functions.analyze-candidate]
verify_jwt = false

[functions.receive-n8n-analysis]
verify_jwt = false

[functions.test-n8n-endpoint]
verify_jwt = false

[functions.send-resume-to-n8n]
verify_jwt = false

[functions.create-default-users]
verify_jwt = false

[functions.schedule-interview]
verify_jwt = false

[functions.schedule-inperson-interview]
verify_jwt = false

[functions.test-google-credentials]
verify_jwt = false

[functions.get-google-refresh-token]
verify_jwt = false

[functions.update-secret]
verify_jwt = false

[functions.refresh-google-token]
verify_jwt = false

[functions.send-whatsapp-notification]
verify_jwt = false

[functions.send-to-n8n-interview]
verify_jwt = false